

const state = {
    floors: [],
    floor: {},
    room_types: [],
    rooms: [],
    paid_services: [],
    reservations: [],
    available_room_types: [],
    selected_rooms: [],
    selected_payments: [],
    invoice: [],
    reservation_paid_service: {},
    type: "price",
    recent_checkins: [],
    todays_checkins: [],
    todays_checkouts: [],
    room_types_with_rooms: [],
    available_rooms_today: [],
    house_keepings: [],
    expenses: [],
    expense_categories: [],
    guests: [],
    invoices: [],
    reports: [],
    payments: [],
    dashboard_details: {},
    all_paid_services: [],
    all_cold_drinks: [],
    reservation_cold_drinks: [],
    invoice_card_details: [],
    oyo_reports: [],
    // hotelDetails: {
    //     name: "Shri Sai Palace",
    //     addressLine1: "Kankanady pumpwell",
    //     addressLine2: "near capitanio school(padil), Mangalore",
    //     zipcode: "575002",
    //     mailId: "contact@srisaipalace.com",
    //     mobile: "+91 900 883 5974",
    //     gst: "29AEEFS3771A1Z2",
    // },
    // hotelDetails: {
    //     name: "White House Inn",
    //     addressLine1: "336-1 To 336-7/V, White House Inn, Veenu Complex",
    //     addressLine2: "Main Road, Kudapura, Udupi, Karnataka",
    //     zipcode: "576201",
    //     mailId: "contact@whitehouseinn.in",
    //     mobile: "+91 91485 08737",
    //     gst: "29AFFPP5198E1Z0",

    // },
    // hotelDetails: {
    //     name: "Hotel Kalyani International",
    //     addressLine1: "Near Mulky Bus Station, Bappanad Temple Road",
    //     addressLine2: "Opp Fish Market, Mangaluru, Karnataka",
    //     zipcode: "574154",
    //     mailId: "kalyaniinternationalmulki@gmail.com",
    //     mobile: "0824 2293333",
    //     gst: "NULL",
    // },
    // hotelDetails: {
    //     name: "Hotel Surya",
    //     addressLine1: "Near Mulky Bus Station, Bappanad Temple Road",
    //     addressLine2: "Opp Fish Market, Mangaluru, Karnataka",
    //     zipcode: "574154",
    //     mailId: "surya@gmail.com",
    //     mobile: "0824 0000000",
    //     gst: "NULL",
    // },
    hotelDetails: {
        name: "Sai Arya",
        addressLine1: "Lodging and Party Hall",
        addressLine2: "Opp Ganesh Medicals, Pumpwell, Mangalore",
        zipcode: "575002",
        mailId: "saiarya@gmail.com",
        mobile: "0824-2433644, 2435644",
        gst: "29ADPFS5012G1ZV",
    },
}

export default state
