

const state = {

    floors: [],
    floor: {},
    room_types: [],
    rooms: [],
    paid_services: [],
    reservations: [],
    available_room_types: [],
    selected_rooms: [],
    selected_payments: [],
    invoice: [],
    reservation_paid_service: {},
    type: "price",
    recent_checkins: [],
    todays_checkins: [],
    todays_checkouts: [],
    room_types_with_rooms: [],
    available_rooms_today: [],
    house_keepings: [],
    expenses: [],
    expense_categories: [],
    guests: [],
    invoices: [],
    reports: [],
    payments: [],
    dashboard_details: {},
    all_paid_services: [],
    all_cold_drinks: [],
    reservation_cold_drinks: [],
    invoice_card_details: [],
    oyo_reports: [],
    oyo_card_details: [],
    awaiting_checkout_id: [],
    oyo_bookings_id: [],
    total_rooms: [],
    walkin_rooms_id: [],
    windowWidth: null,
    activeUserInfo: {},

}

export default state
